patch

diff --git a/.github/workflows/functional_test_v2.yaml b/.github/workflows/functional_test_v2.yaml
--- a/.github/workflows/functional_test_v2.yaml
+++ b/.github/workflows/functional_test_v2.yaml
@@ -10,7 +10,7 @@ env:
   # We limit cache download as a whole to 5 minutes.
   SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
 jobs:
-  kubernetes-test:
+  kind-kubernetes-test:
     env:
       KUBECONFIG: /tmp/kube-config-splunk-otel-collector-chart-functional-testing
       KUBE_TEST_ENV: kind
@@ -20,13 +20,12 @@ jobs:
         # The kubernetes_version matrix entries are currently following native Kubernetes version support and +1, see: https://endoflife.date/kubernetes
         # To check latest versions, see: https://hub.docker.com/r/kindest/node/tags
         k8s-version:
-          # TODO: Add 1.30 support once Kind publishes an official 1.30 image
+          - v1.30.0 # Support: 28 Apr 2025 - 28 Jun 2025
           - v1.29.0 # Support: 28 Dec 2024 - 28 Feb 2025
           - v1.28.0 # Support: 28 Aug 2024 - 28 Oct 2024
           - v1.27.3  # Support: 28 Apr 2024 - 28 Jun 2024
-          - v1.26.6 # Support: 28 Dec 2023 - 28 Feb 2024
           # Test current +1 out-of-date Kubernetes version to cover EKS's extended support version matrix
-          - v1.25.11 # Support: 27 Aug 2023 - 27 Oct 2023
+          - v1.26.6 # Support: 28 Dec 2023 - 28 Feb 2024
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -59,14 +58,30 @@ jobs:
       - name: Deploy cert-manager
         run: |
           make cert-manager
-      - name: run functional tests
+      - name: Run functional tests
         run: |
           cd functional_tests
-          go test -v
+          go test -v || { \
+            echo "Running splunk_kubernetes_debug_info.sh script to collect debug information."; \
+            ./tools/splunk_kubernetes_debug_info.sh; \
+            exit 1; \
+          }
+      - name: Upload Test Failure Info Artifact
+        if: ${{ failure() }}
+        id: failure-info-artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: splunk_kubernetes_debug_info_${{ matrix.k8s-version }}
+          path: ${{ github.workspace }}/*.zip
+          retention-days: 3
+          overwrite: true
+      - name: Output Test Failure Info Artifact URL
+        if: ${{ failure() }}
+        run: echo 'Artifact URL is ${{ steps.failure-info-artifact.outputs.artifact-url }}'
 
   eks-test:
     name: Test helm install in EKS - credentials needed
-    needs: kubernetes-test
+    needs: kind-kubernetes-test
     if: github.event.pull_request.head.repo.full_name == github.repository
     concurrency:
       group: eks-access
@@ -105,7 +120,7 @@ jobs:
       - name: Deploy cert-manager
         run: |
           make cert-manager
-      - name: run functional tests
+      - name: Run functional tests
         env:
           HOST_ENDPOINT: 0.0.0.0
         run: |
@@ -113,7 +128,7 @@ jobs:
           go test -v
   eks-upgrade-test:
     name: Test helm upgrade in EKS - credentials needed
-    needs: kubernetes-test
+    needs: kind-kubernetes-test
     if: github.event.pull_request.head.repo.full_name == github.repository
     concurrency:
       group: eks-access
@@ -177,7 +192,7 @@ jobs:
       - name: Deploy cert-manager
         run: |
           make cert-manager
-      - name: run functional tests
+      - name: Run functional tests
         env:
           HOST_ENDPOINT: 0.0.0.0
         run: |
@@ -186,7 +201,7 @@ jobs:
 
   gke-autopilot-test:
     name: Test helm install in GKE/Autopilot - credentials needed
-    needs: kubernetes-test
+    needs: kind-kubernetes-test
     if: github.event.pull_request.head.repo.full_name == github.repository
     concurrency:
       group: gke-autopilot-access
@@ -224,7 +239,7 @@ jobs:
       - name: Update dependencies
         run: |
           make dep-update
-      - name: run functional tests
+      - name: Run functional tests
         env:
           HOST_ENDPOINT: 0.0.0.0
         run: |
@@ -233,7 +248,7 @@ jobs:
 
   gke-autopilot-upgrade-test:
     name: Test helm upgrade in GKE/Autopilot - credentials needed
-    needs: kubernetes-test
+    needs: kind-kubernetes-test
     if: github.event.pull_request.head.repo.full_name == github.repository
     concurrency:
       group: gke-autopilot-access
@@ -292,7 +307,7 @@ jobs:
           cd base
           helm dependency update helm-charts/splunk-otel-collector
           helm install sock helm-charts/splunk-otel-collector --set cloudProvider=gcp --set distribution=gke/autopilot --set splunkObservability.realm=us0 --set splunkObservability.accessToken=xxxxx
-      - name: run functional tests
+      - name: Run functional tests
         env:
           HOST_ENDPOINT: 0.0.0.0
         run: |
@@ -301,7 +316,7 @@ jobs:
 
   aks-windows-test:
     name: Test helm install in AKS - credentials needed
-    needs: kubernetes-test
+    needs: kind-kubernetes-test
     if: github.event.pull_request.head.repo.full_name == github.repository
     concurrency:
       group: aks-windows-group
@@ -340,7 +355,7 @@ jobs:
       - name: Update dependencies
         run: |
           make dep-update
-      - name: run functional tests
+      - name: Run functional tests
         env:
           HOST_ENDPOINT: 0.0.0.0
         run: |
