patch

diff --git a/.github/workflows/update_instrumentation_dependencies.yaml b/.github/workflows/update_instrumentation_dependencies.yaml
--- a/.github/workflows/update_instrumentation_dependencies.yaml
+++ b/.github/workflows/update_instrumentation_dependencies.yaml
@@ -29,11 +29,7 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Set Git Config
-        if: ${{ steps.swizzle_version.outputs.NEED_UPDATE == 1 }}
-        run: |
-          # Set global Git config for author and committer
-          ./ci_scripts/base_util.sh setup_git
+      - uses: chainguard-dev/actions/setup-gitsign@main
 
       - name: Update Version
         id: swizzle_version
@@ -63,6 +59,7 @@ jobs:
           git --no-pager diff
 
       - name: PR the new version
+        id: swizzle_pr
         if: ${{ steps.swizzle_version.outputs.NEED_UPDATE == 1 }}
         uses: peter-evans/create-pull-request@v5
         with:
@@ -84,38 +81,40 @@ jobs:
         if: ${{ steps.swizzle_version.outputs.NEED_UPDATE == 1 }}
         run: |
 
-          # Fetch the latest changes from the remote repository
-          git fetch
+          # Fetch the latest changes from the remote repository including any new branches
+          git fetch --all
 
-          # Check out the existing "update-${{ matrix.language }}" branch
-          git checkout "update-${{ matrix.language }}" || git checkout -b "update-${{ matrix.language }}"
-
-      - name: Get PR Issue Number
-        if: ${{ steps.swizzle_version.outputs.NEED_UPDATE == 1 }}
-        id: pr_info
-        run: |
-          PR_URL=$(jq -r '.pull_request.html_url' $GITHUB_EVENT_PATH)
-          PR_ISSUE_NUMBER=$(basename $PR_URL)
-          echo "PR_ISSUE_NUMBER=$PR_ISSUE_NUMBER" >> $GITHUB_ENV
+          # Attempt to check out the existing remote branch
+          if git show-ref --quiet --verify "refs/remotes/origin/update-${{ matrix.language }}"; then
+            # The remote branch exists, so check it out
+            git checkout "update-${{ matrix.language }}"
+            git pull origin "update-${{ matrix.language }}"
+          else
+            # If the remote branch does not exist, fail the job
+            echo "Remote branch 'update-${{ matrix.language }}' does not exist."
+            exit 1
+          fi
 
       - name: Create Changelog
         if: ${{ steps.swizzle_version.outputs.NEED_UPDATE == 1 }}
         run: |
-          make chlog-new CHANGE_TYPE=enhancement COMPONENT=operator NOTE="Bump ${{ matrix.language }} to ${{ steps.swizzle_version.outputs.TAG_UPSTREAM }} in ${{ env.VALUES_YAML }}" ISSUES=${{ env.PR_ISSUE_NUMBER }}
+          # Run the update script and handle errors
+          # Emits output env vars swizzle_version.outputs.TAG_LOCAL and steps.swizzle_version.outputs.TAG_UPSTREAM
+          ./ci_scripts/update-images-operator-splunk.sh ${{ matrix.language }} $DEBUG_ARG || exit 1
 
-      - name: Commit and Push Changelog
+          echo "Rendering chart template..."
+          make render
+
+          make chlog-new CHANGE_TYPE=enhancement COMPONENT=operator NOTE="Bump ${{ matrix.language }} to ${{ steps.swizzle_version.outputs.TAG_UPSTREAM }} in ${{ env.VALUES_YAML }}" ISSUES=[${{ steps.swizzle_pr.outputs.pull-request-number }}]
+
+      - name: Update PR with changelog
         if: ${{ steps.swizzle_version.outputs.NEED_UPDATE == 1 }}
-        run: |
-          # Debug
-          echo "jv debug"
-          git config --global user.email
-          git config --global user.name
-
-          # Add all changes and files
-          git add .
-
-          # Commit the changelog with a message
-          git commit -m "Add changelog for PR #${{ env.PR_ISSUE_NUMBER }}"
-
-          # Push the changes to the PR branch
-          git push origin "update-${{ matrix.language }}"
+        uses: peter-evans/create-pull-request@v5
+        with:
+          commit-message: Update ${{ matrix.language }} instrumentation version
+          committer: release-bot <ssg-srv-gh-o11y-gdi@splunk.com>
+          body: Use the latest version of ${{ matrix.language }}
+          branch: "update-${{ matrix.language }}" # Same branch name for all PRs
+          base: main
+          delete-branch: true
+          modify-outputs: false
